#!/bin/sh
# original repo code: https://github.com/realattila/clean_git_commit_message

commit_msg_file=$1
commit_msg=$(cat $commit_msg_file)

template_matched=0

# List of valid commit message prefixes
correctCommitMsgFormat=(
  "⭐ feature:"
  "🛠️ fix:"
  "🔃 refactor:"
  "💫 style:"
  "📄 document:"
  "🧪 test:"
  "🚀 release:"
  "🗑️ remove:"
  "🔼 upgrade:"
  "📦 add:",
  "🧹 chore:"
)


correctCommitMsgTemplate=(
  "⭐ feature:{Your message}"
  "🛠️ fix:{Your message}"
  "🔃 refactor:{Your message}"
  "💫 style:{Your message}"
  "📄 document:{Your message}"
  "🧪 test:{Your message}"
  "🚀 release:{Your message}"
  "🗑️ remove:{Your message}"
  "🔼 upgrade:{Your message}"
  "📦 add:{Your message}",
  "🧹 chore:{Your message}"
)

# Function to check if the commit message starts with one of the prefixes
check_commit_message() {
  local message="$1"
  for prefix in "${correctCommitMsgFormat[@]}"; do
    if [[ "$message" == "$prefix"* ]]; then
      template_matched=1
      break
    fi
  done
}

check_commit_message "$commit_msg"

if [ $template_matched -eq 0 ]; then
  echo "Error: Invalid commit message format. Commit message should start with one of the following prefixes:"
  for prefix in "${correctCommitMsgTemplate[@]}"; do
    echo "  $prefix"
  done
  exit 1
fi
